#!/usr/bin/env python

import rospy
import serial
from std_msgs.msg import String



def publisher():

	arduino= serial.Serial('/dev/ttyUSB0',baudrate=9600,timeout=1)
	arduino.flush()

	pub= rospy.Publisher('string_publish', String, queue_size=10)
	rate= rospy.Rate(1)

	msg_to_publish= String()

	while not rospy.is_shutdown():
		string_to_publish = arduino.readline().decode('utf-8').rstrip()

		msg_to_publish.data= string_to_publish
		pub.publish(msg_to_publish)

		print string_to_publish

		rate.sleep()

if __name__ == "__main__":
	rospy.init_node("simple_publisher")
	publisher()